[ 2024-12-09 19:01:18,337 ] werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.10.186:8080
[ 2024-12-09 19:01:18,338 ] werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2024-12-09 19:01:19,483 ] werkzeug - INFO - 127.0.0.1 - - [09/Dec/2024 19:01:19] "GET / HTTP/1.1" 200 -
[ 2024-12-09 19:01:21,134 ] root - INFO - Updated DATA_DOWNLOAD_URL to: https://drive.google.com/file/d/1ECfl3dtYyfivY8kYPq7RHUBTjC-2vf61/view?usp=share_link
[ 2024-12-09 19:01:21,135 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2024-12-09 19:01:21,137 ] root - INFO - Getting the data from URL
[ 2024-12-09 19:01:21,138 ] root - ERROR - Error during training: Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\pipeline\training_pipeline.py] line number [98] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\pipeline\training_pipeline.py] line number [33] error message [name 'data_url' is not defined]]
[ 2024-12-09 19:01:21,139 ] werkzeug - INFO - 127.0.0.1 - - [09/Dec/2024 19:01:21] "[35m[1mPOST /train HTTP/1.1[0m" 500 -
[ 2024-12-09 19:01:23,030 ] root - INFO - Updated DATA_DOWNLOAD_URL to: https://drive.google.com/file/d/1ECfl3dtYyfivY8kYPq7RHUBTjC-2vf61/view?usp=share_link
[ 2024-12-09 19:01:23,031 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2024-12-09 19:01:23,031 ] root - INFO - Getting the data from URL
[ 2024-12-09 19:01:23,031 ] root - ERROR - Error during training: Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\pipeline\training_pipeline.py] line number [98] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\pipeline\training_pipeline.py] line number [33] error message [name 'data_url' is not defined]]
[ 2024-12-09 19:01:23,031 ] werkzeug - INFO - 127.0.0.1 - - [09/Dec/2024 19:01:23] "[35m[1mPOST /train HTTP/1.1[0m" 500 -
